Feature/ticket 7/purchase presentation layer
luiggy-mamani-jalafund/DDD-CinemaReservationSystem pull request #10
Opened 2024-10-04 16:43 UTC by luiggy-mamani-jalafund

# US-07: Purchase - Presentation Layer

 ## What did I do it?
- Implemented purchase form in the presentation layer

## How did I do it?
- Implemented Popup
- Implemented purchase fields as molecules and their styles
- Implemented purchase form  using the popup and fields modules

## Why did I do it?
To help in the purchase user history.

![image](https://github.com/user-attachments/assets/e8a73e28-93a7-4962-b374-f2197f4c83da)

2024-10-04 16:45 UTC, luiggy-mamani-jalafund commented
![](https://github.trello.services/images/mini-trello-icon.png) [ID-07: Purchase](https://trello.com/c/wCEnN67I/12-id-07-purchase)

2024-10-07 04:53 UTC, salet-gutierrez-jalafund requested changes

2024-10-07 04:53 UTC, salet-gutierrez-jalafund commented on web-frontend/src/app/movies/[id]/page.js
> +    console.log(showtimes);
remove this impression

2024-10-07 12:53 UTC, salet-gutierrez-jalafund requested changes

2024-10-07 12:53 UTC, salet-gutierrez-jalafund commented on web-frontend/src/components/template/theaters/Theater.jsx
> +                            console.log(res[i].hours[j]);
delete console.log

2024-10-07 12:53 UTC, salet-gutierrez-jalafund commented on web-frontend/src/utils/data_fetchers/MoviesFetcher.js
> +    console.log(`http://localhost:5011/api/Showtime/${movieId}`);
delete console.log

2024-10-07 15:17 UTC, salet-gutierrez-jalafund approved these changes

2024-10-07 15:18 UTC, merged