chore: initialize web-frontend with next.js
luiggy-mamani-jalafund/DDD-CinemaReservationSystem pull request #3
Opened 2024-09-24 15:24 UTC by salet-gutierrez-jalafund

### What did I do?
I initialized the program for the frontend side with the chosen technology of next.js

### Why did I do it?
So that the group could start developing the view.

### How did I do it?
I followed the steps to run a nextjs command for a website and according to the notes and acceptance criteria that are in the US

[folder structure](https://github.com/luiggy-mamani-jalafund/DDD-CinemaReservationSystem/wiki/Folder-structure)

2024-09-24 15:25 UTC, salet-gutierrez-jalafund commented
![](https://github.trello.services/images/mini-trello-icon.png) [ID-02: Set Up Frontend Environment with Next.js](https://trello.com/c/3FzjRXLE/4-id-02-set-up-frontend-environment-with-nextjs)

2024-09-25 14:19 UTC, luiggy-mamani-jalafund requested changes
please move the fonts directory to the public directory

2024-09-25 14:19 UTC, luiggy-mamani-jalafund commented on web-frontend/src/app/styles/globals.scss
> +$background-light: #ffffff;
I guess this is the reset css file, so please move it to the base folder

2024-09-25 14:31 UTC, salet-gutierrez-jalafund commented
> please move the fonts directory to the public directory

In the folder structure that is within the wiki ([folder structure](https://github.com/luiggy-mamani-jalafund/DDD-CinemaReservationSystem/wiki/Folder-structure)) it is explained why the fonts are being entered into that folder.

2024-09-25 14:36 UTC, luiggy-mamani-jalafund commented
> > please move the fonts directory to the public directory
> 
> In the folder structure that is within the wiki ([folder structure](https://github.com/luiggy-mamani-jalafund/DDD-CinemaReservationSystem/wiki/Folder-structure)) it is explained why the fonts are being entered into that folder.

The public folder stores public files such as fonts, and CSS fonts must be configured to use them.

![Screenshot from 2024-09-25 10-33-14](https://github.com/user-attachments/assets/04fec9ba-3eb4-4121-8edb-79983e0daa94)

2024-09-25 15:02 UTC, luiggy-mamani-jalafund commented
please move the components, pages, services, and styles at the same height of the app.

Also, move the public folder to the same height of the src
![2024-09-25_11-02](https://github.com/user-attachments/assets/c5768507-965a-4ead-870a-5dd834e29b4f)

2024-09-26 20:55 UTC, luiggy-mamani-jalafund approved these changes

2024-09-26 20:55 UTC, merged